
export const ROUTES = {
  HOME: '/',
  LIST_DOCTORS: '/list-doctors',
  VIEW_DOCTOR: '/view-doctor',   
  USER: {
    REGISTER: '/user/register',
    OTP: '/user/otp',
    LOGIN: '/user/login',
    FORGOT_PASSWORD: '/user/forgot-password',
    RESET_PASSWORD: '/user/reset-password',
    PROFILE: '/user/profile',
    BOOK_SLOT: '/user/book-slot',
    PAYMENT: '/user/payment',
    THANK_YOU: '/user/thank-you',
    WALLET: '/user/wallet',
    VIEW_PRESCRIPTION: (preId: string) => `/user/view-prescription/${preId}`,
    CHAT_LIST: (userId: string) => `/user/chats/${userId}`,
    CHAT: 'user/chat',
  },
  DOCTOR: {
    REGISTER: '/doctor/register',
    OTP: '/doctor/otp',
    REG_CONFIRM: '/doctor/reg-confirm',
    LOGIN: '/doctor/login',
    FORGOT_PASSWORD: '/doctor/forgot-password',
    RESET_PASSWORD: '/doctor/reset-password',
    PROFILE: '/doctor/profile',
    AVAILABILITIES: '/doctor/availabilities',
    ADD_PRESCRIPTION: '/doctor/add-prescription',
    VIEW_PRESCRIPTION: (preId: string) => `/doctor/view-prescription/${preId}`,
    CHAT_LIST: (doctorId: string) => `/doctor/chats/${doctorId}`, 
    SINGLE_CHAT: '/doctor/single-chat',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    FORGOT_PASSWORD: '/admin/forgot-password',
    RESET_PASSWORD: '/admin/reset-password',
    DASHBOARD: '/admin/dashboard',
    LIST_UNAPPROVED_DOCTORS: '/admin/list-unapproved-doctors',
    DOCTOR_DETAILS: '/admin/doctor-details',
    LIST_USERS: '/admin/list-users',
    LIST_DOCTORS: '/admin/list-doctors',
    DOCTORS_APPOINTMENTS: '/admin/doctors-appointments',
  },
};
